project:
  type: website
  output-dir: docs 

website:
  title: "C. Iordachescu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Skills.qmd
      - href: posts.qmd
        text: Posts

format:
  html:
    theme: sandstone
    css: styles.css
    toc: TRUE

editor: visual

