project:
  type: website
  output-dir: docs 

website:
  title: "C.A. Iordachescu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Hobbies.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

